name: Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false # Evita problemas de credenciais persistentes

      - name: Clean up git config
        run: |
          git config --global --unset http.https://github.com/.extraheader || true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pip_lock.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install kivy kivymd pyrebase pycryptodome setuptools

      - name: Set up Buildozer
        run: |
          pip install buildozer
          sudo apt-get install -y \
            python3-pip \
            python3-setuptools \
            python3-virtualenv \
            openjdk-8-jdk \
            unzip \
            zlib1g-dev \
            libncurses5-dev \
            libffi-dev \
            libgmp-dev

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2
        with:
          ndk-version: '21.4.7075529'
          api-level: '31'

      - name: Set environment variable
        run: |
          echo "MY_VAR=My Value" >> $GITHUB_ENV

      - name: Build APK
        run: buildozer android debug
